services:
  db:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports: !override ["127.0.0.1:27017:27017"]
    restart: unless-stopped

  livekit:
    command: --config /etc/livekit.yaml --bind 0.0.0.0
    volumes:
      - ./priv/livekit/livekit.prod.yaml:/etc/livekit.yaml:ro
    restart: unless-stopped

  livekit-tls:
    restart: unless-stopped
    volumes: !override
      - ./priv/livekit/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/pomoroom-tfm-eva.polandcentral.cloudapp.azure.com:/etc/letsencrypt/live/pomoroom-tfm-eva.polandcentral.cloudapp.azure.com:ro
      - /etc/letsencrypt/archive/pomoroom-tfm-eva.polandcentral.cloudapp.azure.com:/etc/letsencrypt/archive/pomoroom-tfm-eva.polandcentral.cloudapp.azure.com:ro
