services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pomoroom-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: abc123.
    ports:
      - "27017:27017"

  livekit:
    image: livekit/livekit-server:latest
    container_name: pomoroom-livekit
    network_mode: host
    command: --config /etc/livekit.yaml --dev --bind 0.0.0.0
    volumes:
      - ./priv/livekit/livekit.yaml:/etc/livekit.yaml:ro

  livekit-tls:
    image: nginx:alpine
    container_name: pomoroom-livekit-tls
    network_mode: host
    depends_on:
      - livekit
    volumes:
      - ./priv/livekit/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./priv/cert:/certs:ro
