import Config

# Configure MongoDB
config :pomoroom, :db, database: "pomoroom_dev", username: "mongo", password: "abc123."

# LiveKit configuration
#
# - api_key / api_secret: default credentials for `livekit-server --dev`
# - ws_port: browser connection via TLS proxy (wss://)
# - admin_url: backend → LiveKit (direct HTTP, no proxy)
#
# Note:
# When the app runs over HTTPS, browsers block insecure ws:// connections.
# For this reason, WebSocket traffic is routed through a TLS proxy (port 7443).

config :pomoroom, :livekit,
  api_key: "devkey",
  api_secret: "secret",
  ws_port: 7443,
  admin_url: "http://localhost:7880"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pomoroom, PomoroomWeb.Endpoint,
  # Bound to all interfaces so other devices (e.g. over a tunnel like ngrok,
  # to share a real link with anyone) can reach the dev server. Set PHX_HOST
  # (and PHX_PORT/PHX_SCHEME if not the ngrok default of 443/https) so
  # generated invite links point somewhere those devices can actually
  # resolve — e.g. `PHX_HOST=abcd1234.ngrok-free.app mix phx.server`.
  # Defaults to "localhost"/4001/https when unset, so normal solo dev is
  # unaffected.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  https: [
    ip: {0, 0, 0, 0},
    port: 4001,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  url: [
    host: System.get_env("PHX_HOST") || "localhost",
    port: String.to_integer(System.get_env("PHX_PORT") || "4001"),
    scheme: System.get_env("PHX_SCHEME") || "https"
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "FMZZ7pjyXrdh2KEEgfaJFYWHpawPZgbDMekMpy+wSMH7mJPgPqaF2dlPAphrKWOl",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pomoroom, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pomoroom, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :pomoroom, PomoroomWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/pomoroom_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pomoroom, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
